import { OnlineContainer } from "@/components/OnlineContainer";
import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Header } from "../../../components/Header";

export const metadata: Metadata = {
  title: "Notificações",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <OnlineContainer>
    <Box style={{ background: "#EBEBEB", padding: 2 }}>
        <Header />
        {children}
      </Box>
    </OnlineContainer>
    </>
  );
}
