import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider, useMediaQuery } from "@mui/material";
import "./globals.scss";
import { theme } from "../theme";
import { Container } from "@/components/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <Container>
          {children}
          </Container>
        </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
