import { Container } from "@/components/Container";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
      <meta name="theme-color" content="#1aff90" />
      </head>
      <body>
        <AppRouterCacheProvider>
          <Container>
          {children}
          </Container>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
