version: "3.7"

services:
  # MongoDB service remains unchanged
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - "27017:27017"

  # MariaDB service remains unchanged
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql

  # Redis service remains unchanged
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  # Nextcloud service remains unchanged
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html

  # Nginx Proxy Manager service
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80  # Proxy Manager UI
      - '81:81'
      - 443:443  # HTTPS for Proxy Manager UI and hosted domains
    environment:
      - USE_HTTPS=true
      - DEFAULT_SERVER_LETSENCRYPT=true  # Enable automatic Let's Encrypt SSL certificate provisioning
      - DEFAULT_SERVER_MAX_CONNECTIONS=200  # Adjust according to your needs
      - DB_USER=admin@example.com
      - DB_PASSWORD=changeme
      - DB_NAME=nginx_proxy_manager
      - VIRTUAL_HOST_IP=your_server_ip_address  # Replace with your server's external IP address
      - NGINX_PROXY_MANAGER_HOST_REDIRECT=https://your_domain.com  # Replace with your actual domain
    volumes:
      - ./data:/data  # Persist Nginx Proxy Manager data
      - ./letsencrypt:/etc/letsencrypt  # Persist Let's Encrypt certificates (optional)
      - ./ssl:/etc/ssl  # Mount custom SSL certificates (optional)
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

volumes:
  db-data: {}
  nextcloud: {}
  # Additional volumes for Nginx Proxy Manager
  data: {}  # Persist Nginx Proxy Manager data
  letsencrypt: {}  # Persist Let's Encrypt certificates (optional)
  ssl: {}  # Mount custom SSL certificates (optional)
