version: "3.7"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mailcow-network

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mailcow-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mailcow-network

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    networks:
      - mailcow-network

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - "81:81"
      - 443:443
    environment:
      - DEFAULT_SERVER_LETSENCRYPT=true
      - DEFAULT_SERVER_MAX_CONNECTIONS=200
      - DB_USER=admin@example.com
      - DB_PASSWORD=changeme
      - DB_NAME=nginx_proxy_manager
      - USE_HTTPS=false
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./ssl:/etc/ssl
    networks:
      - mailcow-network

networks:
  mailcow-network:
    driver: bridge

volumes:
  db-data: {}
  nextcloud: {}
  data: {}
  letsencrypt: {}
  ssl: {}
  mail-data:
  mail-state:
  mail-logs:
  mail-config:
  roundcube-data:
  roundcube-config:
